name: Sync Rote to Notion

on:
  schedule:
    # 每天运行一次
    - cron: '0 0 * * *'

jobs:
  rote_to_notion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Sync Rote content to Notion
        run: python sync_to_notion.py
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          ROTE_API_KEY: ${{ secrets.ROTE_API_KEY }}
